#!/usr/bin/env python3
"""Check the port against the original game code.

Runs functions of the original SIMDIRT.DLL from your install in an x86 emulator and the same
inputs through the Rust port (`sc3k-dump diffref`), then compares the results:

  rng   cRZRandom: every method, random and edge-case arguments, many seeds
  dirt  cSC3DirtGenerator::GenerateRandom: the four vertex maps, the sea level and the
        sequence of cRZRandom calls, over a matrix of seeds, sizes, difficulties and options

Exits 0 when everything matches, 1 on any difference. See docs/re-notes/diffcheck.md.

  tools/diffcheck/run.py all --seeds 5 --report docs/accuracy.md --image docs/screenshots/accuracy.png
"""

import argparse
import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

import checks  # noqa: E402
import rust  # noqa: E402
from emu import WINDOWS_FPCW, Emu  # noqa: E402
from targets import SIMDIRT  # noqa: E402

RNG_NAMES = {
    "next_u32": "RandomUint32Uniform()",
    "uniform": "RandomUint32Uniform(n)",
    "range": "RandomSint32RangeUniform",
    "gaussian_fast": "RandomSint32RangeGaussianFast",
    "range_min_of_two": "min of two draws (0x1001BCA4)",
    "double": "RandomDoubleUniform",
    "double_range": "RandomDoubleRangeUniform",
}


def rows_for(rng_stats, dirt_cases):
    rows = []
    if rng_stats:
        for op, s in rng_stats.items():
            detail = f"{s.calls} calls"
            if s.max_ulps:
                detail += f", worst {s.max_ulps} ulp"
            rows.append(("cRZRandom", RNG_NAMES[op], s.rate(), detail))
    if dirt_cases:
        n = len(dirt_cases)
        mean = lambda m: sum(c.equal[m] for c in dirt_cases) / n  # noqa: E731
        detail = f"{n} case{'s' if n != 1 else ''}"
        rows += [
            ("Terrain generator", "Identical terrains", sum(c.ok() for c in dirt_cases) / n, detail),
            ("Terrain generator", "Sea level", sum(c.sea[0] == c.sea[1] for c in dirt_cases) / n,
             detail),
            ("Terrain generator", "RNG call sequence",
             sum(not c.first_call for c in dirt_cases) / n, detail),
        ]
        rows += [("Terrain generator", f"{m.capitalize()} per vertex", mean(m), "all vertices")
                 for m in checks.MAPS]
    return rows


def report(path, rows, rng_stats, dirt_cases, footer):
    out = ["# Decomp accuracy", "",
           "Generated by `tools/diffcheck/run.py`: the original code runs in an x86 emulator and is",
           "compared with the port on the same inputs. See `docs/re-notes/diffcheck.md`.", "",
           f"{footer}.", "", "| Check | | Match | |", "|---|---|---:|---|"]
    out += [f"| {sec} | {label} | {rate * 100:.2f}% | {detail} |" for sec, label, rate, detail in rows]
    firsts = [(RNG_NAMES[op], s.first) for op, s in (rng_stats or {}).items() if s.first]
    if firsts:
        out += ["", "## First cRZRandom difference per method", ""]
        out += [f"- **{name}**: {first}" for name, first in firsts]
    bad = [c for c in dirt_cases or [] if not c.ok()]
    if bad:
        out += ["", f"## Terrain cases that differ ({len(bad)} of {len(dirt_cases)})", "",
                "| Case | Sea level | Altitude | Water | Flora | Salt | First difference | First RNG call that differs |",
                "|---|---|---:|---:|---:|---:|---|---|"]
        for c in bad[:50]:
            eq = " | ".join(f"{c.equal[m] * 100:.2f}%" for m in checks.MAPS)
            out.append(f"| {c.label()} | {c.sea[0]} / {c.sea[1]} | {eq} | {c.first_vertex} | "
                       f"{c.first_call} |")
        if len(bad) > 50:
            out.append(f"\n{len(bad) - 50} more not shown.")
    Path(path).write_text("\n".join(out) + "\n")


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("what", nargs="?", default="all", choices=["rng", "dirt", "all"])
    ap.add_argument("--seeds", type=int, default=5, help="seeds per check (default 5)")
    ap.add_argument("--sizes", default="64,128,256", help="map sizes for the terrain check")
    ap.add_argument("--rng-calls", type=int, default=400, help="cRZRandom calls per seed")
    ap.add_argument("--dll", help="SIMDIRT.DLL (default $SC3K_DATA/Apps/SIMDIRT.DLL)")
    ap.add_argument("--fpcw", type=lambda s: int(s, 0), default=WINDOWS_FPCW,
                    help="x87 control word (default 0x027F, 53-bit precision as on Windows)")
    ap.add_argument("--report", help="write a markdown report here")
    ap.add_argument("--image", help="write the README accuracy image here (needs dirt)")
    args = ap.parse_args()

    dll = args.dll
    if not dll:
        data = os.environ.get("SC3K_DATA")
        if not data:
            sys.exit("set SC3K_DATA to the SimCity 3000 Unlimited install root, or pass --dll")
        dll = Path(data) / "Apps" / SIMDIRT.dll
    if not Path(dll).exists():
        sys.exit(f"{dll}: not found")

    print("building sc3k-dump ...", file=sys.stderr)
    exe = rust.build()
    make_emu = lambda: Emu(dll, fpcw=args.fpcw)  # noqa: E731
    seeds = [1 + 0x9E3779B9 * i & 0x7FFFFFFF for i in range(args.seeds)]
    rng_stats = dirt_cases = None

    if args.what in ("rng", "all"):
        rng_stats = checks.check_rng(make_emu(), SIMDIRT, exe, seeds, args.rng_calls)
        for op, s in rng_stats.items():
            print(f"{RNG_NAMES[op]:34} {s.exact:6}/{s.calls:<6} {s.rate() * 100:7.2f}%"
                  + (f"  worst {s.max_ulps} ulp" if s.max_ulps else ""))
            if s.first:
                print(f"    first difference: {s.first}")

    if args.what in ("dirt", "all"):
        sizes = [int(s) for s in args.sizes.split(",")]
        cases = checks.dirt_matrix(seeds, sizes)

        def progress(i, n, c):
            eq = " ".join(f"{m} {c.equal[m] * 100:6.2f}%" for m in checks.MAPS)
            mark = "ok  " if c.ok() else "DIFF"
            print(f"[{i + 1:3}/{n}] {mark} {c.label()}  sea {c.sea[0]}/{c.sea[1]}  {eq}")
            if not c.ok():
                if c.first_vertex:
                    print(f"           first difference: {c.first_vertex}")
                if c.first_call:
                    print(f"           first RNG difference: {c.first_call}")

        dirt_cases = checks.check_dirt(make_emu, SIMDIRT, exe, cases, progress)

    rows = rows_for(rng_stats, dirt_cases)
    parts = [f"{args.seeds} seeds"]
    if rng_stats:
        parts.append(f"{sum(s.calls for s in rng_stats.values())} cRZRandom calls")
    if dirt_cases:
        parts.append(f"{len(dirt_cases)} terrains")
    footer = ", ".join(parts) + f", x87 control word {args.fpcw:#06x}"
    if args.report:
        report(args.report, rows, rng_stats, dirt_cases, footer)
        print(f"wrote {args.report}")
    if args.image:
        if not dirt_cases:
            sys.exit("--image needs the dirt check")
        import picture
        picture.render(args.image, dirt_cases[0], rows, footer)
        print(f"wrote {args.image}")

    failed = [r for r in rows if r[2] != 1.0]
    print("all checks match" if not failed else f"{len(failed)} checks differ")
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
